# Generated by Django 4.0.4 on 2022-05-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level_field_class', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Grade',
        ),
    ]
