# Generated by Django 4.0.4 on 2022-04-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
