# Generated by Django 4.0.4 on 2022-04-16 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='id_inst',
        ),
    ]
